#!/bin/bash
if [ "${1}" != "/" ]; then
    cp ~/server/filehost/index.html ~/server/filehost"${1}"index.html || stat .
fi
cd ~/server/filehost"${1}" || return
echo '' > ~/server/filehost"${1}"list.html
for file in *
do
    if [ "$file" != "refresh_filelist" ]; then
        if [ "$file" != "index.html" ]; then
            if [ "$file" != "list.html" ]; then
                # echo '<a href="'${file}'" style="margin: 0; display: inline-block; font-size: initial; position: relative; width: 20%;">'${file}'</a>' >> ~/server/filehost/list.html
                echo '<a href="/filehost'${1}${file}'">'${file}'</a><br>' >> ~/server/filehost"${1}"list.html
                # sed -i ':a;N;$!ba;s/\n//g' ~/server/filehost"${1}"list.html
            fi
        fi
    fi
done